
import {
  Brain,
  Sparkles,
  CheckCircle2,
  Lightbulb,
  ChevronRight,
  Copy,
  Wand2,
  Check,
} from "lucide-react";

import { useState } from "react";
import toast from "react-hot-toast";

const AIResultPanel = ({ aiResult, onUseTitle }) => {
  const [copiedSection, setCopiedSection] = useState(null);

  if (!aiResult) return null;

  const copyToClipboard = async (text, section) => {
    try {
      await navigator.clipboard.writeText(text);

      setCopiedSection(section);

      toast.success(`${section} copied`);

      setTimeout(() => {
        setCopiedSection(null);
      }, 2000);
    } catch (error) {
      toast.error("Failed to copy");
    }
  };
  

  const renderCopyButton = (section, text) => (
    <button
      onClick={() => copyToClipboard(text, section)}
      className="p-2 rounded-lg hover:bg-gray-100 transition-colors"
    >
      {copiedSection === section ? (
        <Check className="w-4 h-4 text-green-600" />
      ) : (
        <Copy className="w-4 h-4 text-gray-400 hover:text-gray-700" />
      )}
    </button>
  );

  return (
    <div className="w-full bg-white border border-gray-200 rounded-3xl shadow-sm overflow-hidden">
      {/* HEADER */}
      <div className="border-b border-gray-100 px-6 py-5">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-[#7C3AED] flex items-center justify-center shadow-sm">
              <Brain className="w-6 h-6 text-white" />
            </div>

            <div>
              <h2 className="text-xl font-semibold text-gray-900 tracking-tight">
                AI Insights
              </h2>

              <p className="text-sm text-gray-500 mt-1 flex items-center gap-1.5">
                <Sparkles size={14} className="text-[#7C3AED]" />
                Generated from your note content
              </p>
            </div>
          </div>

          <div className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#F5F3FF] border border-[#DDD6FE]">
            <div className="w-2 h-2 rounded-full bg-green-500"></div>

            <span className="text-xs font-medium text-[#6D28D9]">
              Analysis Complete
            </span>
          </div>
        </div>
      </div>

      {/* CONTENT */}
      <div className="p-6 space-y-6">
        {/* SUMMARY */}
        <section className="rounded-2xl border border-gray-200 bg-[#FAFAFC] overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-[#F3F0FF] flex items-center justify-center">
                <Sparkles size={17} className="text-[#7C3AED]" />
              </div>

              <div>
                <h3 className="text-sm font-semibold text-gray-900">
                  Summary
                </h3>

                <p className="text-xs text-gray-500">
                  Concise overview generated by AI
                </p>
              </div>
            </div>

            {renderCopyButton("Summary", aiResult.summary)}
          </div>

          <div className="px-5 py-5">
            <p className="text-[15px] leading-7 text-gray-700">
              {aiResult.summary}
            </p>
          </div>
        </section>

        {/* ACTION ITEMS */}
        {aiResult.action_items &&
          aiResult.action_items.length > 0 && (
            <section className="rounded-2xl border border-gray-200 bg-white overflow-hidden">
              <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-orange-50 flex items-center justify-center">
                    <CheckCircle2
                      size={17}
                      className="text-orange-500"
                    />
                  </div>

                  <div>
                    <h3 className="text-sm font-semibold text-gray-900">
                      Action Items
                    </h3>

                    <p className="text-xs text-gray-500">
                      Suggested next steps from the note
                    </p>
                  </div>
                </div>

                {renderCopyButton(
                  "Action Items",
                  aiResult.action_items
                    .map((item, i) => `${i + 1}. ${item}`)
                    .join("\n")
                )}
              </div>

              <div className="p-5 space-y-3">
                {aiResult.action_items.map((item, index) => (
                  <div
                    key={index}
                    className="flex items-start gap-3 rounded-xl border border-gray-200 bg-[#FAFAFC] px-4 py-3 hover:border-gray-300 transition-colors"
                  >
                    <div className="w-6 h-6 rounded-lg bg-orange-100 text-orange-600 flex items-center justify-center text-xs font-semibold flex-shrink-0 mt-0.5">
                      {index + 1}
                    </div>

                    <div className="flex items-start gap-2 flex-1">
                      <ChevronRight
                        size={15}
                        className="text-gray-400 mt-1"
                      />

                      <p className="text-sm text-gray-700 leading-6">
                        {item}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

        {/* SUGGESTED TITLE */}
        {aiResult.suggested_title && (
          <section className="rounded-2xl border border-gray-200 bg-white overflow-hidden">
            <div className="flex items-center gap-3 px-5 py-4 border-b border-gray-200">
              <div className="w-9 h-9 rounded-xl bg-blue-50 flex items-center justify-center">
                <Lightbulb
                  size={17}
                  className="text-blue-600"
                />
              </div>

              <div>
                <h3 className="text-sm font-semibold text-gray-900">
                  Suggested Title
                </h3>

                <p className="text-xs text-gray-500">
                  AI-generated title recommendation
                </p>
              </div>
            </div>

            <div className="p-5">
              <div className="rounded-2xl border border-blue-100 bg-[#F8FAFF] px-5 py-5">
                <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-5">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
                      <Wand2
                        size={18}
                        className="text-blue-600"
                      />
                    </div>

                    <div>
                      <p className="text-xs font-medium uppercase tracking-wide text-blue-500 mb-1">
                        Suggested Heading
                      </p>

                      <h4 className="text-lg font-semibold text-gray-900 leading-relaxed">
                        {aiResult.suggested_title}
                      </h4>
                    </div>
                  </div>

                  <button
                    onClick={() =>
                      onUseTitle(aiResult.suggested_title)
                    }
                    className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-[#7C3AED] hover:bg-[#6D28D9] text-white text-sm font-medium transition-all duration-200 shadow-sm whitespace-nowrap"
                  >
                    <CheckCircle2 size={16} />
                    Use Title
                  </button>
                </div>
              </div>
            </div>
          </section>
        )}
      </div>

      {/* FOOTER */}
      <div className="border-t border-gray-100 bg-[#FAFAFC] px-6 py-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2 text-xs text-gray-500">
            <Sparkles size={12} className="text-[#7C3AED]" />

            <span>
              AI-generated content may require human review
            </span>
          </div>

          <div className="text-xs text-gray-400">
            Peblo AI Workspace
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIResultPanel;